/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/what-are-tokens',
        'concepts/what-is-search',
        'concepts/what-are-containers',
        'concepts/access-controls',
        'concepts/what-is-the-proxy',
        'concepts/what-are-reactors',
        'concepts/what-are-mats',
      ],
    },
    {
      type: 'category',
      label: 'Expressions',
      link: {
        type: 'doc',
        id: 'expressions/index',
      },
      items: [
        'expressions/filters',
        'expressions/detokenization',
        'expressions/aliasing',
        'expressions/fingerprints',
        'expressions/masks',
        'expressions/search-indexes',
      ],
    },
  ],
  api: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'api',
      },
      items: [
        'api/authentication',
        'api/request-correlation',
        'api/pagination',
        'api/errors',
        'api/ip-addresses',
        'api/rate-limits',
      ],
    },
    {
      type: 'category',
      label: 'Applications',
      link: {
        type: 'doc',
        id: 'api/applications/applications',
      },
      items: ['api/applications/permissions'],
    },
    'api/logs',
    {
      type: 'category',
      label: 'Proxies',
      link: {
        type: 'doc',
        id: 'api/proxies/proxies',
      },
      items: ['api/proxies/invoke-proxy'],
    },
    {
      type: 'category',
      label: 'Reactors',
      link: {
        type: 'doc',
        id: 'api/reactors/reactors',
      },
      items: ['api/reactors/reactor-formulas'],
    },
    {
      type: 'category',
      label: 'Tenants',
      link: {
        type: 'doc',
        id: 'api/tenants/tenants',
      },
      items: ['api/tenants/tenant-members'],
    },
    {
      type: 'category',
      label: 'Tokens',
      link: {
        type: 'doc',
        id: 'api/tokens/tokens',
      },
      items: [
        'api/tokens/tokenize',
        'api/tokens/token-types',
        'api/tokens/search',
        'api/tokens/token-associations'
      ],
    },
    'api/deprecations'
  ],
  sdk: [
    'sdks',
    {
      type: 'category',
      label: 'Server-side SDKs',
      items: [{
        type: 'autogenerated',
        dirName: 'sdks/server-side',
      }],
    },
    {
      type: 'category',
      label: 'Web SDKs',
      items: [
        {
          type: 'category',
          label: 'JavaScript Elements',
          link: {
            type: 'doc',
            id: 'sdks/web/javascript-elements',
          },
          items: [
            'sdks/web/elements/content-security-policy',
            'sdks/web/elements/types',
            'sdks/web/elements/lifecycle',
            'sdks/web/elements/options',
          ],
        },
        'sdks/web/react-elements'
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Mobile SDKs',
    //   items: [{
    //     type: 'autogenerated',
    //     dirName: 'sdks/mobile',
    //   }],
    // },
  ]
};

module.exports = sidebars;
