name: Pull Request

on:
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --immutable --no-progress --ignore-scripts

      - name: Build
        run: yarn build

  pr-security-check:
    name: PR Security Check
    uses: Basis-Theory/public-security-workflows/.github/workflows/pr-check.yml@master
    secrets: inherit